#!/usr/bin/env python
#
# a2lc_null -- just read pairs of input lines and log something.


import sys

import syslog


me = sys.argv [0].split ('/') [-1]

syslog.openlog ("a2lc_null", syslog.LOG_PID | syslog.LOG_PERROR)


class LinePairIterator ():

	def __init__ (self, stream):
		self.stream = stream

	def __iter__ (self):
		return self

	def next (self):
		ln1 = self.stream.readline ()
		if ln1 == '':
			raise StopIteration
		if ln1 [-1:] == '\n':
			ln1 = ln1 [:-1]
		ln2 = self.stream.readline ()
		if ln2 == '':
			syslog.syslog (syslog.LOG_ERR, "Input stream closed; dropping sole DN %s" % ln1)
			raise StopIteration
		if ln2 [-1:] == '\n':
			ln2 = ln2 [:-1]
		return (ln1,ln2)


linepairreader = LinePairIterator (sys.stdin)


for (dn,at) in linepairreader:

	syslog.syslog (syslog.LOG_INFO, "DN  %s" % dn)
	syslog.syslog (syslog.LOG_INFO, "LCS %s" % at)

